OPENAI_API_KEY = "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"

GOOGLE_API_KEY = "AIzaSyDyrGBixyCOsxHcJwLFkCWjhe0QLTyUtQU"

pwd = "Satelix_PoV_v0.1"